NUMPY QUICKSTART

In [2]:
#importing numpy library
import numpy as np

ARRAY CREATION

In [3]:
# creating arrays
arr1 = np.array([[2,5,7], [8,3,5], [2,9,4]])
arr2 = np.array([1,6,2])

In [5]:
# finding the dimensions 
dim = arr1.ndim
dim

2

In [6]:
# checking type of array
arr2.dtype

dtype('int32')

In [12]:
# creating array full of zeros
zero = np.zeros((2,3))
zero


array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# creating array full of ones
one = np.ones((3,4)) 
one

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

PRINTING ARRAYS

In [16]:
# 1D arrnagement
a = np.arange(4)
a

array([0, 1, 2, 3])

In [19]:
# 2D arrangement
b = np.arange(10).reshape(2,5)
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
# 3D arranement
c = np.arange(18).reshape(3,3,2)
c

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]]])

BASIC OPERATIONS

In [29]:
x = np.array([54,66,87,34,23])
x

array([54, 66, 87, 34, 23])

In [30]:
y = np.array([35,76,4,78,91])
y

array([35, 76,  4, 78, 91])

In [32]:
# addition
addn = x + y
addn

array([ 89, 142,  91, 112, 114])

In [33]:
# subtraction
subt = x - y
subt

array([ 19, -10,  83, -44, -68])

In [38]:
# multiplication
multi = x ** 3
multi

array([157464, 287496, 658503,  39304,  12167], dtype=int32)

In [36]:
# comparative operation (boolean)
y < 56

array([ True, False,  True, False, False])

MATRICES

In [42]:
m = np.array([[1,2,3],
      [4,5,6],
      [7,8,9]])
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
n = np.array([[3,4,5],
      [6,7,8],
      [9,1,2]])
n

array([[3, 4, 5],
       [6, 7, 8],
       [9, 1, 2]])

In [45]:
# ELEMENTWISE PRODUCT
m*n

array([[ 3,  8, 15],
       [24, 35, 48],
       [63,  8, 18]])

In [46]:
# MATRIX PRODUCT
m@n

array([[ 42,  21,  27],
       [ 96,  57,  72],
       [150,  93, 117]])

In [47]:
#ANOTHER MATRIX PRODUCT
m.dot(n)

array([[ 42,  21,  27],
       [ 96,  57,  72],
       [150,  93, 117]])

MATHEMATICAL OPERATION

In [50]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
n

array([[3, 4, 5],
       [6, 7, 8],
       [9, 1, 2]])

In [56]:
# sum of each column
m.sum()

45

In [54]:
# min of each row
n.min()

1

In [55]:
# cumulative sum along each row
m.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

INDEXING, SPLICING, INTERATING

In [57]:
x

array([54, 66, 87, 34, 23])

In [58]:
y

array([35, 76,  4, 78, 91])

In [59]:
x[2:4]

array([87, 34])

In [60]:
y[:3]

array([35, 76,  4])

In [61]:
# reversing the array
x[::-1]

array([23, 34, 87, 66, 54])

In [66]:
#splicing by 2 spaces
y[::2]

array([35,  4, 91])

In [68]:
# iterating
for i in x:
    print(i)

54
66
87
34
23


In [69]:
arr1

array([[2, 5, 7],
       [8, 3, 5],
       [2, 9, 4]])

In [70]:
# transvered array
arr1.T

array([[2, 8, 2],
       [5, 3, 9],
       [7, 5, 4]])

In [71]:
# Here it shows that it doesnt affect the original array
arr1

array([[2, 5, 7],
       [8, 3, 5],
       [2, 9, 4]])

SPLITTING

In [73]:
# splitting the array
np.hsplit(arr1,3)

[array([[2],
        [8],
        [2]]),
 array([[5],
        [3],
        [9]]),
 array([[7],
        [5],
        [4]])]

In [76]:
x

array([54, 66, 87, 34, 23])

In [77]:
# sorting the array
np.sort(x)

array([23, 34, 54, 66, 87])

In [78]:
y

array([35, 76,  4, 78, 91])

In [80]:
# joining the 2 arrays
np.concatenate((x,y), axis = 0)

array([54, 66, 87, 34, 23, 35, 76,  4, 78, 91])

RESHAPING THE ARRAY AND CONVERTING 1D INTO 2D

In [81]:
r = np.arange(10)
r

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [82]:
# reshaping the array
s = r.reshape(5,2)
s

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [86]:
# flattening the array
s.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

UNIQUE VALUES

In [84]:
u = np.array([1,1,2,2,3,3,4,4,5,5])
u

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5])

In [85]:
# fetching unique values
uniq = np.unique(u)
uniq

array([1, 2, 3, 4, 5])

In [87]:
# to know more about the array
u?