Subtract the 1D Array *arr2* from the 2D array *arr1*, such that each item of *arr2* subtracts from respective row of *arr1*

Ex

arr1 = `[[x1, x2 , x3], [y1, y2, y3], [z1,z2,z3]]`

arr2 = `[x,y,z]`

Result `[ [ x1-x, x2-x, x3-x],` etc

In [48]:
import numpy as np
arr1 = np.array([[2,5,7], [8,3,5], [2,9,4]])
arr2 = np.array([1,6,2])

# using indexing
var1 = arr1[0] - arr2[0]
var2 = arr1[1] - arr2[1]
var3 = arr1[2] - arr2[2]
print(var1)
print(var2)
print(var3)

[1 4 6]
[ 2 -3 -1]
[0 7 2]


In [15]:
# merging the results using concatenate function
var = np.concatenate((var1, var2, var3))
print(var)

[ 1  4  6  2 -3 -1  0  7  2]


Given a 1D Array, find the local maxima (numbers surrounded by 2 smaller numbers)

In [34]:
arr = np.array([2,5,7,8,3,5,2,9,4])

# to find the maximum number in the array - 
#it is different than local maxima
maximum = arr.max()
print(maximum)        

9


In [35]:
# to find the local maxima
for i in range(9):
    if arr[i] > arr[i-1] and arr[i] > arr[i+1]:
        print(arr[i])

8
5
9


Given two n x m Arrays, compute the average of elements in matching subarrays

Ex

arr1      
`[[1,1],[2,2],[3,3]]`

arr2      
`[[1,1],[2,2],[3,3]]`

result:
`[1,2,3]`



In [47]:
arr3 = np.array([[2,5], [8,3], [2,9]])
arr4 = np.array([[3,2], [7,4], [9,4]])

#avg1 = np.mean(arr3[0], arr4[0])

avg1 = (arr3[0] + arr4[0]) / 2
avg2 = (arr3[1] + arr4[1]) / 2
avg3 = (arr3[2] + arr4[2]) / 2
print(np.concatenate((avg1,avg2,avg3)))

[2.5 3.5 7.5 3.5 5.5 6.5]
